### ISSUE TITLE
Does echo work with React Native?

### ISSUE THREAD

**Issue by ahmed-wagdi** [laravel/echo#126]
I'm trying to integrate echo with React Native, i followed the installation guide in the docs and added the following:

```
import Echo from "laravel-echo"

const EchoNotifications = new Echo({
    broadcaster: 'pusher',
    key: '30c47b6ab35c9be45426'
});
```

Which gives me the error `can't find variable: Pusher` and points to this line in echo.js:
`this.pusher = new Pusher(this.options.key, this.options);`

**Comment by orangecoloured** [comment]
Apparently not, at least in the current state.
There's no `io` reference in the `socketio-connector.ts`.

It could probably resolve the issue if we could pass the reference in the options next to the `broadcaster`.

**Comment by hareku** [comment]
I solved it with this code.
(Nuxt.js)

```
import Echo from 'laravel-echo'
import Pusher from 'pusher-js'

window.Pusher = Pusher

export default ({ app }) => {
  app.echo = new Echo({
    broadcaster: 'pusher',
    key: 'your-pusher-key'
  })
}
```

**Comment by okaufmann** [comment]
When the next version will be released you can pass the io-module as option parameter and it does check if window if its available. See details: https://github.com/laravel/echo/pull/160
I did not tests it with pusher yet...

**Comment by driesvints** [comment]
Going to close this because like @okaufmann said it should now be easily possible to do this.

**Comment by okaufmann** [comment]
As of today it can work because of this PR https://github.com/laravel/echo/pull/186

**Comment by danfebraa** [comment]
Managed to solve mine using with these code block:


```yaml
/**Note: I am using homestead and on my homestead file I add these lines
This will allow me to let me access my local machine within the network, 
and I can also access this via the emulator (Android)*/

networks:
    - type: "public_network"
      bridge: "en1: Wi-Fi (AirPort)"
```
```php
/**In your App.js, function App()*/
useEffect(() => {

        Pusher.logToConsole = true;

        let PusherClient = new Pusher('{YOUR_KEY}',{
            cluster: 'mt1',
            wsHost: '{YOUR_HOST}',
            wsPort: '6001',
            enabledTransports: ['ws'],
            forceTLS: false
        });

        let echo = new Echo({
            broadcaster: 'pusher',
            client: PusherClient
        });

        echo.channel('home').listen('NewMessage', (e) => {
            alert()
        });

    })
```

**Comment by danfebraa** [comment]
@okaufmann using the PR you mentioned. PR #186 
Managed to solve mine using with these code block:


```yaml
/**Note: I am using homestead and on my homestead file I add these lines
This will allow me to let me access my local machine within the network, 
and I can also access this via the emulator (Android)*/

networks:
    - type: "public_network"
      bridge: "en1: Wi-Fi (AirPort)"
```
```php
/**In your App.js, function App()*/
useEffect(() => {

        Pusher.logToConsole = true;

        let PusherClient = new Pusher('{YOUR_KEY}',{
            cluster: 'mt1',
            wsHost: '{YOUR_HOST}',
            wsPort: '6001',
            enabledTransports: ['ws'],
            forceTLS: false
        });

        let echo = new Echo({
            broadcaster: 'pusher',
            client: PusherClient
        });

        echo.channel('home').listen('NewMessage', (e) => {
            alert()
        });

    })
```

**Comment by danfebraa** [comment]
@okaufmann using the PR you mentioned. PR #186 
Managed to solve mine using with these code block:


```yaml
/**Note: I am using homestead and on my homestead file I add these lines
This will allow me to let me access my local machine within the network, 
and I can also access this via the emulator (Android)*/

- ssh into your homestead and do `ifconfig ` and get the `eth2` ip address, that would be your access.

networks:
    - type: "public_network"
      bridge: "en1: Wi-Fi (AirPort)"
```
```php
/**In your App.js, function App()*/
useEffect(() => {

        Pusher.logToConsole = true;

        let PusherClient = new Pusher('{YOUR_KEY}',{
            cluster: 'mt1',
            wsHost: '{YOUR_HOST}',
            wsPort: '6001',
            enabledTransports: ['ws'],
            forceTLS: false
        });

        let echo = new Echo({
            broadcaster: 'pusher',
            client: PusherClient
        });

        echo.channel('home').listen('NewMessage', (e) => {
            alert()
        });

    })
```

**Comment by danfebraa** [comment]
@okaufmann using the PR you mentioned. PR #186 
Managed to solve mine using with these code block:


```yaml
/**Note: I am using homestead and on my homestead file I add these lines
This will allow me to let me access my local machine within the network, 
and I can also access this via the emulator (Android)*/

- ssh into your homestead and do `ifconfig ` and get the `eth2` ip address, that would be your access.

networks:
    - type: "public_network"
      bridge: "en1: Wi-Fi (AirPort)"
```
```jsx
/**In your App.js*/
import Pusher from 'pusher-js/react-native';
import Echo from 'laravel-echo';

/**In your App.js, function App()*/
useEffect(() => {

        Pusher.logToConsole = true;

        let PusherClient = new Pusher('{YOUR_KEY}',{
            cluster: 'mt1',
            wsHost: '{YOUR_HOST}',
            wsPort: '6001',
            enabledTransports: ['ws'],
            forceTLS: false
        });

        let echo = new Echo({
            broadcaster: 'pusher',
            client: PusherClient
        });

        echo.channel('home').listen('NewMessage', (e) => {
            alert()
        });

    })
```
